name: testenv
channels:
  - conda-forge
dependencies:
    - pip
    - numpy >=1.13
    - scipy >=1.0.0
    - pandas >=0.21.1
    - matplotlib >=2.1
    - requests
    - xlrd >=1.1
    - xlwt >=1.3
# testing
    - pytest
    - pytest-cov
    - coverage
    - nose
